### ISSUE TITLE
Great walkthru, one issue discovered

### ISSUE THREAD

**Issue by sdluth77** [WillChamness/Dnsmasq-PXE#1] opened 2023-10-31 06:00 UTC
This was an excellent walk-through of the process.  However, I spent much time troubleshooting an issue where this wouldn't work properly and not boot to the menu.  The overall result was UEFI Secure Boot was not supported.  Once I disabled the Secure Boot feature, everything worked.  When secure boot is enabled, you get an NBP Successful error but it then loops back into the UEFI bios screen wanting to select a boot option.

**Comment by WillChamness** [comment] 2023-10-31 18:20
Just to clarify, were you able to install a distro with Secure Boot disabled via PXE? Also, are you able to install normally with Secure Boot enabled through a flashed USB drive (or from the ISO, if you're using a VM)? If yes to both, I believe the problem is that Secure Boot doesn't trust Syslinux.

As mentioned [here](https://github.com/WillChamness/Dnsmasq-PXE#secure-boot), I got an "access denied" error when testing a UEFI virtual machine. In my case, I simply disabled pre-enroll keys, which permanently disables Secure Boot on the virtual machine. 

Syslinux is an old technology. As you can see by [this](https://wiki.archlinux.org/title/Arch_boot_process#Feature_comparison) Arch Linux Wiki page, it is limited in functionality when it comes to UEFI. The UEFI bootloader is unsigned, so Secure boot believes it to be untrustworthy.

Dealing with Secure Boot is likely not worth the trouble, but if you want it enabled, you're probably going to have to do some extra steps. Any modern distro will install a signed bootloader onto the hard drive, so it may be as simple as disabling Secure Boot, installing the distro through PXE, doing a full system update, and re-enabling Secure Boot. I did exactly this as a quick test with a Linux Mint UEFI VM, and everything seems to work fine on first glance. However, if you are dual booting, you will almost certainly have to change some GRUB config files. Possibly even more work if you are using Nvidia.

**Comment by WillChamness** [comment] 2023-11-03 15:58
If there's anything else I can clarify, please let me know. Otherwise, I will close the issue.

**Closed as completed** 2023-11-05 22:29 UTC
